server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdbpostgres
    driver-class-name: org.postgresql.Driver
    username: bankdbuser
    password: bankdbpw
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8060/eureka/

info:
  app:
    name: "account microservice"
    description: "v.1.2.0"

