spring:
  application:
    name: account
  config:
    import: optional:configserver:http://localhost:8071/
  profiles:
    active: qa
  cloud:
    refresh:
      enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8060/eureka/

info:
  app:
    name: "account microservice"
    description: "v.1.2.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted

server:
  port: 80808
