services:
  compliance:
    image: compliance:1.2.0
    container_name: compliance_container
    ports:
      - "8090:8090"
    extends:
      file: config.yml
      service: base-config

  compliance2:
    image: compliance:1.2.0
    container_name: compliance2_container
    ports:
      - "8091:8090"
    extends:
      file: config.yml
      service: base-config

networks:
  cenbankbiz:
    external: true
