services:
  eurekaserver:
    image: eurekaserver:1.2.0
    container_name: eurekaserver_container
    networks:
      - cenbankbiz
    ports:
      - "8060:8060"
    healthcheck:
      test: "curl --fail --silent localhost:8060/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      - SPRING_APPLICATION_NAME=eurekaserver
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/



networks:
  cenbankbiz:
    external: true