build:
  version: "account 1.1.0 QA"

account:
  detail: "QA Current PIC : Thanos"
  contactDetails:
    name: "Thanos - QA Lead"
    email: "jane@jmail.com"
  availability:
    - at Discord
    - at Whatsapp (office hours)