services:
  configserver:
    image: configserver:1.2.0-SNAPSHOT
    container_name: configserver-container
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: config.yml
      service: base-config

networks:
  cenbank:
    driver: "bridge"