spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/dvcsr/config-CenBankMicroservices.git"
          default-label: main
          timeout: 7
          clone-on-start: true
          force-pull: true