spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/dvcsr/config-CenBankMicroservices.git"
          default-label: main
          timeout: 7
          clone-on-start: true
          force-pull: true
    refresh:
      enabled: false

server:
  port: 8071

