services:
  accpostgres:
    image: postgres:alpine
    container_name: bankdb
    environment:
      POSTGRES_DB: bankdbpostgres
      POSTGRES_USER: bankdbuser
      POSTGRES_PASSWORD: bankdbpw
    ports:
      - "5434:5432"
    volumes:
      - bankdb_data:/var/lib/postgresql/data
    networks:
      - cenbankbiz

volumes:
  bankdb_data:

networks:
  cenbankbiz:
    external: true
