services:
  postgres:
    image: postgres:alpine
    container_name: bankdb
    environment:
      POSTGRES_DB: bankdbpostgres
      POSTGRES_USER: bankdbuser
      POSTGRES_PASSWORD: bankdbpw
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 150M
    volumes:
      - bankdb_data:/var/lib/postgresql/data
    networks:
      - bankdb_network

volumes:
  bankdb_data:

networks:
  bankdb_network:
