build:
  version: "compliance 1.1.0 QA"

account:
  detail: "QA Current PIC : Thanos"
  contactDetails:
    name: "Thanos - QA Lead"
    email: "jane@jmail.com"
  availability:
    - @ Discord
    - @ Whatsapp (office hours)