services:
  comppostgres:
    image: postgres:alpine
    container_name: compliancedb
    environment:
      POSTGRES_DB: compliancedbpostgres
      POSTGRES_USER: compliancedbuser
      POSTGRES_PASSWORD: compliancedbpw
    ports:
      - "5433:5432"
    volumes:
      - compliancedb_data:/var/lib/postgresql/data
    networks:
      - cenbankbiz

  accpostgres:
    image: postgres:alpine
    container_name: bankdb
    environment:
      POSTGRES_DB: bankdbpostgres
      POSTGRES_USER: bankdbuser
      POSTGRES_PASSWORD: bankdbpw
    ports:
      - "5434:5432"
    volumes:
      - bankdb_data:/var/lib/postgresql/data
    networks:
      - cenbankbiz

volumes:
  compliancedb_data:
  bankdb_data:
networks:
  cenbankbiz:
    external: true
