services:
  configserver:
    image: configserver:1.2.0
    container_name: configserver-container
    ports:
      - "8071:8071"
    extends:
      file: config.yml
      service: base-config

networks:
  cenbankbiz:
    external: true