services:
  base-config:
    networks:
      - cenbankbiz
    deploy:
      resources:
        limits:
          memory: 500m
    environment:
      - SPRING_PROFILES_ACTIVE=qa
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8060/eureka/